# Generated by Django 4.1.7 on 2025-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_student_full_name_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='year_of_joining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
