# Generated by Django 4.1.7 on 2025-01-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_result_semester_alter_result_grade_totalgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
