# Generated by Django 4.1.7 on 2025-01-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0007_teacher_email_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='year_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
