# Generated by Django 4.1.7 on 2025-01-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_alter_teacher_year_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
