# Generated by Django 4.1.7 on 2025-01-11 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0009_alter_student_year_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='year_of_joining',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
